## The functions below are used to create a special "matrix" object that
## stores a matrix and cache's its inverse. It is assumed that the provided
## matrix is square and invertible.

## The function makeCacheMatrix creates a special "matrix" object that can
## cache its inverse. 
makeCacheMatrix <- function(A = matrix()) {
    
    # initialize inverse Ainv as NULL
    Ainv <- NULL
    
    # nested set function:
    # the provided matrix newA is assigned to the matrix A, while the inverse
    # Ainv is set (back) to NULL - the assignments of A and Ainv is in the
    # enclosing environment
    set <- function(newA) {
        A <<- newA
        Ainv <<- NULL
    }
    
    # nested get function:
    # returns the matrix A
    get <- function() A
    
    # nested setinv function:
    # the provided matrix newAinv is assigned to the matrix inverse Ainv
    setinv <- function(newAinv) Ainv <<- newAinv

    # nested getinv function:
    # returns the inverse matrix Ainv
    getinv <- function() Ainv
    
    # the returned "matrix" object is a list of the get/set and getinv/setinv
    # functions, as defined in the above
    list(set = set, get = get,
         setinv = setinv,
         getinv = getinv)
}


## The function cacheSolve computes the inverse of the special "matrix" object
## that is generated by the makeCacheMatrix function. If the inverse has been
## calculated before for this matrix, the cachesolve retrieves the inverse
## from the cache. Otherwise, the inverse is computed, saved in the cache and
## returned.
cacheSolve <- function(A, ...) {
    
    # get the cached inverse Ainv, using the getinv function
    Ainv <- A$getinv()
    
    # if this inverse is not NULL, return, with the cached inverse as output
    if(!is.null(Ainv)) {
        message("Returning cached inverse.")
        return(Ainv)
    }
    
    # otherwise, compute the inverse Ainv
    matrix <- A$get()
    Ainv <- solve(matrix, ...)
    
    # set the cached inverse Ainv, using the setinv function ..
    A$setinv(Ainv)
    # .. and return the inverse Ainv
    Ainv
}