## The functions below are used to create a special "matrix" object that
## stores a matrix and cache's its inverse. It is assumed that the provided
## matrix is square and invertible.

## The function makeCacheMatrix creates a special "matrix" object that can
## cache its inverse. 
makeCacheMatrix <- function(A = matrix()) {
    
    # initialize inverse Ainv as NULL
    Ainv <- NULL
    
    # define nested set function:
    # the matrix A is set to the eceived matrix newA, the inverse Ainv (back)
    # to NULL - the assignment of A and Ainv is in the enclosing environment
    set <- function(newA) {
        A <<- newA
        Ainv <<- NULL
    }
    
    # define nested get function:
    # returns the matrix A
    get <- function() A
    
    # define nested setinv function:
    # Ainv is set to received matrix newAinv
    setinv <- function(newAinv) Ainv <<- newAinv

    # define nested getinv function:
    # returns the inverse Ainv
    getinv <- function() Ainv
    
    # the returned "matrix" object is a list of the defined get/set and
    # getinv/setinv functions
    list(set = set, get = get,
         setinv = setinv,
         getinv = getinv)
}


## The function cacheSolve computes the inverse of the special "matrix" object
## that is generated by the makeCacheMatrix function. If the inverse has been
## calculated before for this matrix, the cachesolve retrieves the inverse
## from the cache. Otherwise, the inverse is computed, saved in the cache and
## returned.
cacheSolve <- function(A, ...) {
    
    # get the cached inverse Ainv, using getinv
    Ainv <- A$getinv()
    
    # if this inverse is not NULL, return with the cached inverse as output
    if(!is.null(Ainv)) {
        message("Returning cached inverse.")
        return(Ainv)
    }
    
    # otherwise, compute the inverse Ainv
    matrix <- A$get()
    Ainv <- solve(matrix, ...)
    
    # set the cached inverse Ainv, using setinv ..
    A$setinv(Ainv)
    # .. and return the inverse Ainv
    Ainv
}